/**
 * inject-push-sw.js
 * Appends push notification handlers to the sw.js generated by next-pwa.
 * Run after `next build` via package.json "build" script.
 *
 * next-pwa v5 silently ignores worker/index.js on Next.js 16, so we
 * inject the handlers here instead.
 */

const fs = require("fs");
const path = require("path");

const swPath = path.join(__dirname, "..", "public", "sw.js");

if (!fs.existsSync(swPath)) {
  console.error("[inject-push-sw] ❌  public/sw.js not found — run next build first.");
  process.exit(1);
}

const pushHandlers = `

// ─── Push notification handlers (injected by scripts/inject-push-sw.js) ───────

self.addEventListener("push", (event) => {
  if (!event.data) return;

  let payload;
  try {
    payload = event.data.json();
  } catch {
    payload = { title: "Agendify", body: event.data.text(), url: "/agenda" };
  }

  const options = {
    body: payload.body,
    icon: payload.icon || "/icons/icon-192x192.png",
    badge: "/icons/icon-96x96.png",
    data: { url: payload.url || "/agenda" },
    vibrate: [200, 100, 200],
    requireInteraction: false,
    silent: false,
  };

  event.waitUntil(
    self.registration.showNotification(payload.title, options)
  );
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();

  const targetUrl = event.notification.data?.url || "/agenda";

  event.waitUntil(
    clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((clientList) => {
        for (const client of clientList) {
          if ("navigate" in client && "focus" in client) {
            return client.navigate(targetUrl).then(() => client.focus());
          }
        }
        if (clients.openWindow) {
          return clients.openWindow(targetUrl);
        }
      })
  );
});
`;

const current = fs.readFileSync(swPath, "utf8");

// Avoid double-injection if build is run multiple times
if (current.includes("inject-push-sw")) {
  console.log("[inject-push-sw] ✅  Push handlers already present — skipping.");
  process.exit(0);
}

fs.writeFileSync(swPath, current + pushHandlers, "utf8");
console.log("[inject-push-sw] ✅  Push handlers injected into public/sw.js");
